image: "python:3.8"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

mypy:
  stage: Static Analysis
  script:
  - mypy
  
pytest:
  stage: Test
  script:
  - pytest
  