image: continuumio/miniconda3:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PATH: "C:\\Python27"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  
stages:
  - Static Analysis
  - Test
  
pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint -d C0301 bild/*.py
  
mypy:
  stage: Static Analysis
  script:
  - pwd
  - ls -l
  - python -m mypy bild/file.py
  - python -m mypy bild/directory.py

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 bild/*.py

unit_test:
  stage: Test
  script:
  - pwd
  - ls -l
  - export PYTHONPATH="$PYTHONPATH:."
  - python -c "import sys;print(sys.path)"
  - pytest