language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - env: TOXENV=flake8

install:
  - pip install .
  - pip install tox flake8 black

script:
  - black src/ test/
  - tox
