language: python

matrix:
  include:
    - python: 3.8
      env: TOXENV=py38

before_install:
  - mkdir -p ~/.config/cldf/
  - (cd ~/.config/cldf/ && [ -d glottolog ] || git clone --depth 1 https://github.com/glottolog/glottolog.git)
  - (cd ~/.config/cldf/ && [ -d concepticon-data ] || git clone --depth 1 https://github.com/concepticon/concepticon-data.git concepticon)
  - (cd ~/.config/cldf/ && [ -d clts ] || curl -o clts.zip https://zenodo.org/record/3515745/files/cldf-clts/clts-v1.4.1.zip?download=1 && unzip clts.zip && mv cldf-clts-clts-d0dbd4b clts)
  - pip install cldfbench pyglottolog pyconcepticon pyclts
  - cldfbench catconfig
  - cldfbench catinfo
  - pip install tox flake8 black

install:
  - pip install .

script:
  - black src/ test/
  - tox
